### ISSUE TITLE
OpenDKIM Failed to start OpenDKIM Milter.

### ISSUE THREAD

**Issue by Brickelectronic** [takeyamajp/docker-postfix#5]
I think the main.cf is inside the docker (/etc/postfix/main.cf)
If I try to start the opendkim service (on ubuntu 22.04), I get an error).
The reccomendation is to add the following int o the main.cf.
Could you please check this?

```
#Milter - DKIM, DMARC, SPF
#########################################################################

milter_default_action                   = accept
milter_protocol                         = 6

smtpd_milters =
    inet:127.0.0.1:8892

non_smtpd_milters = 
    ${smtpd_milters}
```

**Comment by takeyamajp** [comment]
Thank you for posting your issue of this docker image.
Could you show me the error log of opendkim that you got?

**Comment by Brickelectronic** [comment]
[log.txt](https://github.com/takeyamajp/docker-postfix/files/10609529/log.txt)
[composer.txt](https://github.com/takeyamajp/docker-postfix/files/10609534/composer.txt)
[env.txt](https://github.com/takeyamajp/docker-postfix/files/10609535/env.txt)

Please find attached the log and my composer / env informations. I try to include the files for the
DKIM_KEYS and the SSL_CERT from the ubuntu system to change it if neccesary. Meanwhile I change the
DKUM Cert and I found that in the logs are the first version from setup the docker. Perhaps the
docker read the files only one time and then no change will recognized?
I just starting with Docker and perhaps make some mistakes.
Thank you for your help.

**Comment by takeyamajp** [comment]
This docker image automatically creates SSL certification files and DKIM key files when it starts.
However, if you already have those files, you can replace the contents of the automatically created files with your own.

And this docker image will reload all the configuration next time it starts.

**Comment by takeyamajp** [comment]
According to the log you attached, all services included the OpenDKIM in this docker image seem to have started successfully.
```
2023-02-04 19:44:32,884 INFO supervisord started with pid 1
2023-02-04 19:44:33,886 INFO spawned: 'tail' with pid 27
2023-02-04 19:44:33,888 INFO spawned: 'rsyslog' with pid 28
2023-02-04 19:44:33,890 INFO spawned: 'opendkim' with pid 29
2023-02-04 19:44:33,891 INFO spawned: 'postfix' with pid 30
2023-02-04 19:44:34,893 INFO success: tail entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-02-04 19:44:34,893 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-02-04 19:44:34,893 INFO success: opendkim entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-02-04 19:44:34,893 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Feb  4 19:44:33 a4b6a5bcea98 opendkim[29]: OpenDKIM Filter v2.11.0 starting (args: -f -x /etc/opendkim.conf)
2023-02-04 19:44:35,030 INFO exited: postfix (exit status 0; expected)
Feb  4 19:44:34 a4b6a5bcea98 postfix/postfix-script[100]: starting the Postfix mail system
Feb  4 19:44:35 a4b6a5bcea98 postfix/master[102]: daemon started -- version 3.5.8, configuration /etc/postfix
```

So, if you were not able to send emails normally this time, I think it was highly likely that your configuration problem, not with this docker image.
For example, specifying a string like an email address for AUTH_USER was wrong.

In the configuration below, the user name should be set in your email client will be "user@example.com".
```
DOMAIN_NAME: "example.com"
AUTH_USER: "user"
```

**Comment by Brickelectronic** [comment]
Sending E-Mails is already successful. Only the DMARC will not work, because reload the Docker will not use the own file from the given path. But I will correct the user entry. Perhaps this have an side effect on this.

**Comment by Brickelectronic** [comment]
Now rebuild the Docker will use the DMARC file. And I correct the selector I set wrong.
And now I understand that your Docker will create the DMARC cert automatically from the parameters - I make more than neccessary ;-)
Thank you a lot for your help

**Comment by takeyamajp** [comment]
This Docker image have logged which DKIM key was loaded.
```
default._domainkey      IN      TXT     ( "v=DKIM1; k=rsa; "
          "p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQzPZiFX40pRDL2kkE6uSQs8PQeHT+jfKyT/AYv3Xfri3X/8DnvLHb7H9eZaVQ7DAheoDkhJMRAVx9RwcJEQIDAQAB" )  ; ----- DKIM key default for schwabenstein.org
```

And then the TXT records for DKIM appear not to be configured correctly in your DNS server for your domain 'schwabenstein.org'.
That's one of the reasons why DMARC and DKIM don't work well.
Please check again those configurations.
